### ISSUE TITLE
NFC question

### ISSUE THREAD

**Issue by Ademolght** [pr3y/Bruce#133]
Its possible to load .nfc file if is not , possible add it on Bruce?
Thanks

**Comment by bmorcelli** [comment]
I think that renaming them to .rfid it will be read by Bruce..

They look similar to the .rfid we have in this repo..

**Comment by Ademolght** [comment]
This Nfc repo can work?
https://github.com/UberGuidoZ/Flipper/tree/main/NFC

**Comment by Ademolght** [comment]
But when i see the uberguidoz amiibo repo its 134 pages and when i see the nfc file for Bruce repo its 135 pages

**Comment by bmorcelli** [comment]
I think its not a problem... The problem with AMIIBO is that it nees to "lock" the rfid tag.. @rennancockles told me that it isn't beig done yet.. but I think he is the best guy to answer about it

**Comment by Ademolght** [comment]
I buy rewritable ntag215 card and write the NFC file on I think I can work
