### ISSUE TITLE
Custom GIF viewer in startup

### ISSUE THREAD

**Issue by Ademolght** [pr3y/Bruce#314]
**Feature request.**
Custom GIF viewer for bruce firmware using jpg frame i think can be done esealy using the jpg view
 and i also found this repo for GIF viewer with M5stack https://github.com/tobozo/ESP32-GifPlayer

**Comment by eadmaster** [comment]
it should require this library only 
https://github.com/bitbank2/AnimatedGIF/blob/master/examples/TFT_eSPI_memory/TFT_eSPI_memory.ino

Flipper0 uses a custom file format for animations, but it is B&W only, so i think it's better to stick with standard GIFs:
https://github.com/UberGuidoZ/Flipper/tree/main/Graphics/Animations/PYX

**Comment by Ademolght** [comment]
@eadmaster so i close it

**Comment by eadmaster** [comment]
Gif images could also be used as replacement for the current hardcoded menu icons, i'm testing them here:

https://github.com/eadmaster/Bruce/commit/c7e831e654429eb002030f20bff8f87d3109dc09
